# Generated by Django 2.1.7 on 2019-03-31 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catlin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='has_nested_comments',
            field=models.BooleanField(default=True),
        ),
    ]
