# Generated by Django 2.1.7 on 2019-03-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catlin', '0002_comment_has_nested_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='has_nested_comments',
            field=models.BooleanField(default=False),
        ),
    ]
