# Generated by Django 2.1.7 on 2019-03-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catlin', '0003_auto_20190331_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='has_nested_comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='no_of_nested_comments',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
