# Generated by Django 2.1.7 on 2019-04-01 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catlin', '0004_auto_20190331_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
