# Generated by Django 2.1.7 on 2019-04-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catlin', '0007_auto_20190401_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='comment_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
