# Generated by Django 2.1.7 on 2019-04-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catlin', '0008_category_comment_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.URLField(max_length=100),
        ),
    ]
