# Generated by Django 2.1.7 on 2019-04-04 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catlin', '0009_auto_20190402_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='no_of_nested_comments',
            new_name='comment_count',
        ),
    ]
