# Generated by Django 2.1.7 on 2019-04-16 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catlin', '0012_auto_20190408_1415'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categorymap',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='categorymap',
            name='cat_in_category',
        ),
        migrations.RemoveField(
            model_name='categorymap',
            name='category',
        ),
        migrations.DeleteModel(
            name='CategoryMap',
        ),
    ]
